version: '3.5'

services:
  redis:
    image: redis:latest
    container_name: redis_microwave_db
    networks:
      - deployml_network
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    networks:
      - deployml_network
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - redis

  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0
    volumes:
      - .:/app/api
    ports:
      - 8000:8000
    networks:
      - deployml_network
    depends_on:
      - redis

  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile_front
    volumes:
      - .:/app/front
      - .:/app/front/node_modules
    ports:
      - 3000:3000
    networks:
      - deployml_network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  redis-data:


networks:
  deployml_network:
    driver: bridge


